"""empty message

Revision ID: c8e7a2d44ba0
Revises: 181485afcdba
Create Date: 2022-06-19 12:25:43.225500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e7a2d44ba0'
down_revision = '181485afcdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'release_year')
    # ### end Alembic commands ###
