"""empty message

Revision ID: d9f6e9002cd7
Revises: e4ffef63fced
Create Date: 2022-06-20 22:03:53.679253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9f6e9002cd7'
down_revision = 'e4ffef63fced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_playback',
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.id'], ),
    sa.PrimaryKeyConstraint('phone_id', 'episode_id')
    )
    op.drop_table('playback_episode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playback_episode',
    sa.Column('phone_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('episode_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_time', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='playback_episode_ibfk_1'),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.id'], name='playback_episode_ibfk_2'),
    sa.PrimaryKeyConstraint('phone_id', 'episode_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('episode_playback')
    # ### end Alembic commands ###
